name = "kv"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "KV_BINDING", id = "15ab7451de044296bdea3bdf2b841160" }
]

[[d1_databases]]
binding = "DB"
database_name = "cfdb"
database_id = "4fa75170-04af-4fc2-83d1-499148160ef0"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "7aad2543fff5439f8164abee856ac53a"

[[hyperdrive]]
binding = "METABASE_BINDING"
id = "18cfca7acd35410a87c911481eba98ae"

[triggers]
crons = ["0 3 * * *"]

